quickactions:
    - title: Reboot
      fun: system.reboot
    - title: Reload
      fun: service.restart
      arg: ['lightdm']
    - title: Shutdown
      fun: system.halt

modules:
    - name: tvremote
      options:
        tgt: 'tv-*'
        streams:
            - title: ProPresenter Stream
              url: 'http://sshow.ccc.local:8081/camera.ts'

eauth: pam
